baseURL = 'https://hansvl.nl/'
languageCode = 'en-uk'
title = 'Hans van Luttikhuizen-Ross'
author = 'Hans van Luttikhuizen-Ross'

pluralizelisttitles = false
paginate = 10
enableEmoji = true

RelativeURLs = true
CanonifyURLs = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[Params]
    favicon = "favicon.ico"
    titleImage = 'images/profile.jpg'
    showPrevNextPostNavigation = true
    showRecentPostsOnIndex = true

# Favicons config
# Get your favicons from https://realfavicongenerator.net/
[Params.favicons]
  appleTouchIcon = '/apple-touch-icon.png'
  icon32 = '/favicon-32x32.png'
  icon16 = '/favicon-16x16.png'
  manifest = '/site.webmanifest'
  maskIcon = '/safari-pinned-tab.svg'
  msApplicationTileColor = '#5bbad5'
  themeColor = '#2B2B2B'

# Umami configuration
# https://umami.is/docs/install
[Params.umami]
  enabled = false
  websiteId = "1234567-abcd-efgh-0000-abcdefg1234"
  jsLocation = "https://analytics.example.com/umami.js"

# h-card configuration
# fullName is mandatory
[Params.hcard]
  avatar = "images/profile.jpg"
  fullName = "Hans van Luttikhuizen-Ross"
  pronouns = [ "he", "him" ]
  nickname = "pindab0ter"
  showLocation = true
  city = "Arnhem"
  region = "Gelderland"
  country = "The Netherlands"

# Social icons to be displayed on the front page
[[menu.social]]
  name = "GitHub"
  url = "https://github.com/pindab0ter"

[[menu.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/hansvanluttikhuizen/"

[[menu.social]]
  name = "RSS"
  url = "/index.xml"
  [[menu.social.params]]
    type = "application/rss+xml"

# To make purging of CSS classes work in production
[build]
  writeStats = true

# Syntax highlight settings
[markup]
  [markup.highlight]
    noClasses = false