baseURL = 'https://hansvl.nl/'
languageCode = 'en-uk'
title = 'Hans van Luttikhuizen-Ross'
author = 'Hans van Luttikhuizen-Ross'

pluralizelisttitles = false
paginate = 10
enableEmoji = true
enableGitInfo = true

RelativeURLs = true
CanonifyURLs = true

disqusShortname = "hansvl"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[Params]
    favicon = "favicon.ico"
    titleImage = 'images/profile.jpg'
    showPrevNextPostNavigation = true
    showRecentPostsOnIndex = true

# Favicons config
# Get your favicons from https://realfavicongenerator.net/
[Params.favicons]
  appleTouchIcon = '/apple-touch-icon.png'
  icon32 = '/favicon-32x32.png'
  icon16 = '/favicon-16x16.png'
  manifest = '/site.webmanifest'
  maskIcon = '/safari-pinned-tab.svg'
  msApplicationTileColor = '#5bbad5'
  themeColor = '#2B2B2B'

# Umami configuration
# https://umami.is/docs/install
[Params.umami]
  enabled = true
  websiteId = "88d855a7-4414-40a9-b228-1107ef60aca8"
  jsLocation = "https://analytics.umami.is/script.js"

# Plausible configuration
[Params.plausible]
  enabled = false
  domain = "hansvl.nl"
  jsLocation = "https://plausible.io/js/plausible.js"

# h-card configuration
# fullName is mandatory
[Params.hcard]
  avatar = "images/profile.jpg"
  fullName = "Hans van Luttikhuizen-Ross"
  nickname = "pindab0ter"
  showLocation = true
  city = "Arnhem"
  region = "Gelderland"
  country = "The Netherlands"

# Social icons to be displayed on the front page
[[menu.social]]
  name = "GitHub"
  url = "https://github.com/pindab0ter"

[[menu.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/hansvanluttikhuizen/"

[[menu.social]]
  name = "RSS"
  url = "/rss.xml"
  [[menu.social.params]]
    type = "application/rss+xml"

# To make purging of CSS classes work in production
[build]
  writeStats = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "rss"

# Syntax highlight settings
[markup]
  [markup.highlight]
    noClasses = false

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[imaging]
  quality = 85
  hint = "picture"
  resampleFilter = "Lanczos"

  [imaging.exif]
    disableDate = false
    disableLatLong = true