name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

  # Enables running this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v4
        id: pages

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - run: git lfs checkout

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: |
          hugo \
            --gc \
            --minify \
            --baseURL ${{ steps.pages.outputs.base_url }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
